### ISSUE TITLE
[Enhancement] Smart Issue Decomposition (SID) for CCW - Phase 1 Implementation

### ISSUE THREAD

**Issue by fumiya-kume** [fumiya-kume/FeLangKit#183]
# Smart Issue Decomposition (SID) for CCW - Implementation Specification

## Overview

This specification extends the CCW CLI tool with intelligent issue complexity analysis and guided splitting capabilities. The implementation follows a phased approach, starting with basic complexity detection and evolving toward AI-powered issue decomposition.

## Vision

When Claude Code detects that an issue is too large or complex for efficient implementation, CCW will provide intelligent guidance to help developers break it down into smaller, manageable pieces with proper tracking and dependencies.

### Core Features

- **Complexity Analysis**: Basic text-based complexity scoring
- **User Warnings**: Alert users when issues appear complex  
- **Guidance**: Provide actionable recommendations for manual splitting
- **Foundation**: Build architecture for future AI integration

### Enhanced Workflow

The current 8-step workflow becomes:

1. **Setting up worktree** (unchanged)
2. **Fetching issue data** (unchanged)
3. **🆕 Analyzing issue complexity** (NEW)
   - Basic complexity scoring
   - User warning if complex
4. **Generating analysis** (enhanced with complexity context)
5. **Running Claude Code** (enhanced with complexity awareness)
6. **Validating implementation** (unchanged)
7. **Creating pull request** (unchanged)
8. **Workflow complete** (unchanged)

### Usage Examples

```bash
# Standard usage with complexity analysis
ccw https://github.com/owner/repo/issues/123

# Manual complexity analysis
ccw analyze-issue https://github.com/owner/repo/issues/123

# Batch complexity analysis
ccw analyze-issues --milestone "v2.0" --output complexity-report.json
```

### User Experience

When a complex issue is detected:

```
🤖 Issue Complexity Analysis
┌─────────────────────────────────────────────────────────────────┐
│ Complexity Score: HIGH (7.8/10)                                │
├─────────────────────────────────────────────────────────────────┤
│ Indicators:                                                     │
│   📝 Issue length: 850 words (above average)                   │
│   🏷️  Complex labels: architecture, breaking-change            │
│   💬 Comment activity: 15 comments, 4 participants             │
│   🔧 Technical keywords: API, database, migration              │
│                                                                 │
│ ⚠️  This issue may benefit from being split into smaller parts │
│                                                                 │
│ 💡 Recommendations:                                             │
│   • Consider separating API changes from UI updates            │
│   • Create separate issues for migration tasks                 │
│   • Split testing and documentation into follow-up issues      │
└─────────────────────────────────────────────────────────────────┘

Continue with implementation? (Y/n/help): 
```

### New Package Structure

```
ccw/
├── complexity/
│   ├── analyzer.go          # Issue complexity analysis
│   ├── scoring.go           # Complexity scoring algorithms
│   ├── recommendations.go   # Split recommendations
│   └── types.go            # Complexity analysis types
├── github/
│   ├── analysis.go         # GitHub issue analysis helpers
│   └── enhanced_client.go  # Extended GitHub client
└── reporting/
    ├── complexity_report.go # Complexity analysis reporting
    └── export.go           # Data export functionality
```

### Complexity Metrics

The analyzer will evaluate issues based on:

#### Technical Complexity Indicators:
- **Code Scope**: Number of files/modules likely to be affected
- **Architecture Impact**: Changes to core interfaces, APIs, or data models
- **Dependencies**: External library changes or new dependencies
- **Testing Requirements**: UI tests, integration tests, performance tests needed

#### Specification Clarity Indicators:
- **Requirement Ambiguity**: Vague or unclear requirements
- **Missing Acceptance Criteria**: Lack of clear success conditions
- **Incomplete Context**: Missing background information or constraints
- **Multiple Stakeholders**: Multiple teams or user groups affected

#### Implementation Risk Indicators:
- **Time Estimation**: Likely implementation time > threshold (e.g., 3 days)
- **Review Complexity**: Changes difficult to review in single PR
- **Rollback Risk**: High risk of needing to rollback changes
- **Integration Points**: Multiple system integration points

### Complexity Scoring Algorithm

```yaml
Complexity Score Calculation:
  Technical Weight: 40%
    - Code Scope (0-10): Files affected estimation
    - Architecture Impact (0-10): Core system changes
    - Dependencies (0-10): External dependency changes
    - Testing Requirements (0-10): Test complexity estimation
  
  Specification Weight: 35%
    - Requirement Clarity (0-10): Inverse of ambiguity level
    - Acceptance Criteria (0-10): Completeness of success conditions
    - Context Completeness (0-10): Background information quality
    - Stakeholder Complexity (0-10): Number of affected parties
  
  Risk Weight: 25%
    - Time Estimation (0-10): Expected implementation duration
    - Review Complexity (0-10): PR review difficulty
    - Rollback Risk (0-10): Risk assessment for changes
    - Integration Complexity (0-10): System integration points

Total Score: (Technical × 0.4) + (Specification × 0.35) + (Risk × 0.25)

Thresholds:
  - 0-3: Simple (proceed normally)
  - 4-6: Moderate (proceed with caution)
  - 7-8: Complex (suggest splitting)
  - 9-10: Very Complex (strongly recommend splitting)
```

## Configuration

```yaml
# ccw.yaml - Phase 1 configuration
complexity_analysis:
  enabled: true
  complexity_threshold: 7.0
  
  weights:
    text_length: 0.3
    label_score: 0.2
    activity_level: 0.2
    technical_scope: 0.3
  
  technical_keywords:
    - "API"
    - "database"
    - "migration"
    - "architecture"
    - "breaking change"
    - "performance"
    - "security"
    - "integration"
    - "infrastructure"
    - "deployment"
  
  complex_labels:
    - "epic"
    - "architecture"
    - "breaking-change"
    - "enhancement"
    - "refactoring"
    - "migration"
    - "performance"
    - "security"

ui:
  show_complexity_analysis: true
  complexity_warnings: true
  split_guidance: true

reporting:
  enabled: false  # Disabled by default in Phase 1
```

### Phase 1: MVP (6 weeks)
- **Week 1-2**: Core complexity analysis package
- **Week 3-4**: UI integration and user experience
- **Week 5**: Testing and configuration
- **Week 6**: Documentation and deployment

### Success Metrics for Phase 1
- 70%+ of users find complexity warnings helpful
- 30%+ of flagged issues are manually split by users
- No significant workflow disruption
- Positive user feedback on guidance quality

### Phase 2: Template-Based Splitting (6-8 weeks after Phase 1)
- Pre-defined issue split templates
- GitHub API integration for child issue creation
- Basic dependency tracking via labels
- Project board integration

### Phase 3: AI-Enhanced Analysis (8-12 weeks after Phase 2)
- Claude Code integration for intelligent analysis
- Custom split suggestions based on code structure
- Automated child issue generation
- Advanced dependency detection

### Phase 1 Requirements
- [ ] Basic complexity analysis implemented with configurable scoring
- [ ] UI integration shows complexity warnings when threshold exceeded
- [ ] User can choose to continue or get guidance when complex issue detected
- [ ] Configuration system supports customizable complexity thresholds and weights
- [ ] Command-line interface supports complexity analysis commands
- [ ] Documentation updated with complexity analysis features
- [ ] Tests cover complexity scoring algorithms and edge cases
- [ ] No breaking changes to existing CCW functionality

### Technical Requirements
- [ ] Complexity analysis package with proper interfaces
- [ ] GitHub issue analysis helpers
- [ ] UI components for complexity display and user interaction
- [ ] Configuration management for complexity settings
- [ ] Command-line argument parsing for new features
- [ ] Error handling and graceful degradation
- [ ] Performance benchmarks for analysis speed

### User Experience Requirements
- [ ] Clear, actionable complexity warnings
- [ ] Helpful guidance for issue splitting strategies
- [ ] Non-intrusive integration with existing workflow
- [ ] Configurable behavior for different team preferences
- [ ] Comprehensive help documentation

## Current State Issues

Based on the attached main.go file, there are several linter errors that need to be addressed:

1. **Missing claude.ClaudeContext type** - Need to define this type in the claude package
2. **UI method naming inconsistencies** - Methods should be capitalized (Warning vs warning, Success vs success)
3. **Missing RestoreTerminalState method** - UI cleanup method needs proper casing

These should be fixed as part of the implementation to ensure clean integration.

## Definition of Done

- [ ] All acceptance criteria met
- [ ] Code review completed and approved
- [ ] Unit tests passing with >80% coverage
- [ ] Integration tests validate end-to-end functionality
- [ ] Documentation updated (README, user guide, API docs)
- [ ] Configuration examples provided
- [ ] Performance benchmarks meet requirements
- [ ] No linter errors or warnings
- [ ] Backward compatibility maintained

---

**Labels**: enhancement, ccw, automation, phase-1  
**Milestone**: CCW v2.0  
**Estimated Effort**: 6 weeks  
**Priority**: Medium  

This issue represents the first phase of a comprehensive issue management enhancement for CCW, focusing on providing intelligent guidance to developers about issue complexity without disrupting existing workflows.
